version: 2
updates:
  - package-ecosystem: "npm"
    groups:
      all:
        patterns:
          - "*"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    assignees:
      - tomasvotava
    reviewers:
      - tomasvotava
