name: Build JSDoc

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        with:
          key: ${{runner.os}}-npm-20.x-${{hashFiles('package-lock.json')}}
          path: ~/.npm
      - run: npm clean-install
      # This job will run after a successful eslint, so any errors are rather errors in jsdoc and should be ignored
      - run: npm run docs || true
      - name: Upload exported docs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: out/
