name: Test package

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --verbose clean-install
      - run: npm run lint
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Test
        run: |
          firebase emulators:exec \
            --only auth,firestore,functions,pubsub \
            "npm run test"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tomasvotava/churrizard
