name: Test & lint package

on:
  workflow_call:

jobs:
  test:
    name: Test (node ${{matrix.node-version}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v4
        with:
          key: ${{runner.os}}-npm-${{matrix.node-version}}-${{hashFiles('package-lock.json')}}
          path: ~/.npm
      - uses: actions/cache@v4
        with:
          key: ${{runner.os}}-emulators-${{matrix.node-version}}-${{hashFiles('package-lock.json')}}
          path: ~/.cache/firebase/emulators
      - run: npm --verbose clean-install
      - run: npm run lint
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Test
        run: |
          firebase emulators:exec \
            --only auth,firestore,functions,pubsub \
            "npm run test"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          NODE_VERSION: ${{matrix.node-version}}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tomasvotava/churrizard
          flags: unittests
          env_vars: OS,NODE_VERSION
