name: Create development build

on:
  workflow_dispatch:

jobs:
  get_next_semver:
    uses: ./.github/workflows/_get_next_version.yml

  create-dev-build:
    runs-on: ubuntu-latest
    needs: [get_next_semver]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Set dev build tag
        env:
          NEXT_SEMVER: ${{needs.get_next_semver.outputs.semver}}
        run: |
          BUILD_TAG=${NEXT_SEMVER}-dev.$(date +'%s')
          echo "Creating build with tag ${BUILD_TAG}"
          sed -i package.json 's/"version": ".*"/"vesrion": "'"${BUILD_TAG}"'"/'
          cat package.json
